export const DEMO_CHALLENGES = {
  1: {
    id: 1,
    title: 'Soma de Dois Números',
    level: 'Iniciante',
    category: 'Algoritmos',
    rating: 4.5,
    description: 'Dado um array de inteiros, escreva uma função que retorne os índices dos dois números cuja soma seja igual ao alvo (target) fornecido. Assuma que cada entrada tem exatamente uma solução e o mesmo elemento não pode ser usado duas vezes.\n\nExemplo:\n  Entrada: nums = [2, 7, 11, 15], target = 9\n  Saída: [0, 1] (porque nums[0] + nums[1] = 2 + 7 = 9)',
  },
  2: {
    id: 2,
    title: 'Validação de Parênteses',
    level: 'Iniciante',
    category: 'Estruturas de Dados',
    rating: 4.7,
    description: 'Dada uma string contendo apenas os caracteres "(", ")", "{", "}", "[" e "]", determine se a entrada é válida.\n\nUma entrada é válida quando:\n- Parênteses abertos devem ser fechados pelo mesmo tipo de parêntese.\n- Parênteses abertos devem ser fechados na ordem correta.\n\nExemplo:\n  Entrada: "()[]{}" → Saída: true\n  Entrada: "(]"     → Saída: false',
  },
  3: {
    id: 3,
    title: 'Lista de Tarefas',
    level: 'Intermediário',
    category: 'Back-end',
    rating: 4.2,
    description: 'Crie uma API REST para gerenciar uma lista de tarefas (to-do list) com as seguintes operações:\n\n- GET /tasks        → listar todas as tarefas\n- POST /tasks       → criar uma nova tarefa\n- PUT /tasks/:id    → atualizar uma tarefa\n- DELETE /tasks/:id → remover uma tarefa\n\nCada tarefa deve ter: id, titulo, concluida (boolean), criadaEm.',
  },
  4: {
    id: 4,
    title: 'Inverter String',
    level: 'Iniciante',
    category: 'Algoritmos',
    rating: 4.3,
    description: 'Escreva uma função que receba uma string e retorne ela invertida, sem utilizar o método reverse() nativo.\n\nExemplos:\n  Entrada: "hello"  → Saída: "olleh"\n  Entrada: "CodeLab" → Saída: "beLedoC"\n  Entrada: ""       → Saída: ""\n\nBonus: resolva em O(n) com complexidade de espaço O(1).',
  },
  5: {
    id: 5,
    title: 'Árvore Binária',
    level: 'Avançado',
    category: 'Estruturas de Dados',
    rating: 4.8,
    description: 'Implemente uma árvore binária de busca (BST) com os seguintes métodos:\n\n- insert(value)  → insere um valor na árvore\n- search(value)  → retorna true se o valor existe\n- inOrder()      → retorna array com traversal em-ordem\n- preOrder()     → retorna array com traversal pré-ordem\n- postOrder()    → retorna array com traversal pós-ordem\n\nBonus: implemente remoção de nós.',
  },
  6: {
    id: 6,
    title: 'Sistema de Blog',
    level: 'Intermediário',
    category: 'Back-end',
    rating: 4.6,
    description: 'Desenvolva um sistema de blog completo com autenticação e as seguintes funcionalidades:\n\n- Cadastro e login de usuários com JWT\n- CRUD de posts (criar, listar, editar, excluir)\n- Sistema de comentários por post\n- Posts podem ser marcados como rascunho ou publicado\n- Apenas o autor pode editar ou excluir seu post\n\nUse Express.js + Sequelize (ou outro ORM de sua escolha).',
  },
};
